services:
  - type: worker
    name: djn-broker-bot
    env: python
    buildCommand: "pip install -r requirements.txt && python -c 'import nltk; nltk.download(\"vader_lexicon\")'"
    startCommand: "python schedule_runner.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TZ
        value: Europe/Berlin
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: ALPACA_PAPER_API_KEY
        sync: false
      - key: ALPACA_PAPER_API_SECRET
        sync: false
      - key: ALPACA_LIVE_API_KEY
        sync: false
      - key: ALPACA_LIVE_API_SECRET
        sync: false

